
export const mockFacilities = [
  // Bệnh viện
  {
    id: 'hospital-1',
    name: 'Bệnh viện Chợ Rẫy',
    type: 'hospital',
    lat: 10.7580,
    lng: 106.6600,
    address: '201B Nguyễn Chí Thanh, Quận 5',
    description: 'Bệnh viện đa khoa hạng đặc biệt',
  },
  {
    id: 'hospital-2',
    name: 'Bệnh viện Nhân dân 115',
    type: 'hospital',
    lat: 10.7810,
    lng: 106.6660,
    address: '527 Sư Vạn Hạnh, Quận 10',
    description: 'Bệnh viện đa khoa hạng I',
  },
  {
    id: 'hospital-3',
    name: 'Bệnh viện Đại học Y Dược',
    type: 'hospital',
    lat: 10.7890,
    lng: 106.7050,
    address: '215 Hồng Bàng, Quận 5',
    description: 'Bệnh viện chuyên khoa',
  },

  // Trường học
  {
    id: 'school-1',
    name: 'Đại học Bách Khoa TP.HCM',
    type: 'school',
    lat: 10.7725,
    lng: 106.6576,
    address: '268 Lý Thường Kiệt, Quận 10',
    description: 'Đại học kỹ thuật hàng đầu phía Nam',
  },
  {
    id: 'school-2',
    name: 'Đại học Khoa Học Tự Nhiên',
    type: 'school',
    lat: 10.7628,
    lng: 106.6824,
    address: '227 Nguyễn Văn Cừ, Quận 5',
    description: 'ĐH Quốc Gia TP.HCM',
  },
  {
    id: 'school-3',
    name: 'Đại học Kinh Tế TP.HCM',
    type: 'school',
    lat: 10.7850,
    lng: 106.6960,
    address: '59C Nguyễn Đình Chiểu, Quận 3',
    description: 'Đại học kinh tế hàng đầu',
  },
  {
    id: 'school-4',
    name: 'Đại học Sư Phạm TP.HCM',
    type: 'school',
    lat: 10.7620,
    lng: 106.6830,
    address: '280 An Dương Vương, Quận 5',
    description: 'Đại học sư phạm',
  },
  {
    id: 'school-5',
    name: 'ĐH RMIT Việt Nam',
    type: 'school',
    lat: 10.7292,
    lng: 106.6958,
    address: '702 Nguyễn Văn Linh, Quận 7',
    description: 'Đại học quốc tế',
  },

  // Siêu thị
  {
    id: 'supermarket-1',
    name: 'Vincom Center Đồng Khởi',
    type: 'supermarket',
    lat: 10.7790,
    lng: 106.7016,
    address: '72 Lê Thánh Tôn, Quận 1',
    description: 'Trung tâm thương mại cao cấp',
  },
  {
    id: 'supermarket-2',
    name: 'AEON Mall Bình Tân',
    type: 'supermarket',
    lat: 10.7420,
    lng: 106.6100,
    address: '1 Đường số 17A, Bình Tân',
    description: 'Trung tâm mua sắm lớn',
  },
  {
    id: 'supermarket-3',
    name: 'Co.opmart Lý Thường Kiệt',
    type: 'supermarket',
    lat: 10.7740,
    lng: 106.6610,
    address: '493 Lý Thường Kiệt, Quận 10',
    description: 'Siêu thị tiện lợi',
  },
  {
    id: 'supermarket-4',
    name: 'Emart Gò Vấp',
    type: 'supermarket',
    lat: 10.8230,
    lng: 106.6730,
    address: '366 Phan Văn Trị, Gò Vấp',
    description: 'Siêu thị Hàn Quốc',
  },
  {
    id: 'supermarket-5',
    name: 'Takashimaya Saigon Centre',
    type: 'supermarket',
    lat: 10.7730,
    lng: 106.7000,
    address: '92-94 Nam Kỳ Khởi Nghĩa, Quận 1',
    description: 'Trung tâm mua sắm Nhật Bản',
  },

  // Công viên
  {
    id: 'park-1',
    name: 'Công viên 23/9',
    type: 'park',
    lat: 10.7710,
    lng: 106.6920,
    address: 'Phạm Ngũ Lão, Quận 1',
    description: 'Công viên trung tâm thành phố',
  },
  {
    id: 'park-2',
    name: 'Công viên Tao Đàn',
    type: 'park',
    lat: 10.7770,
    lng: 106.6930,
    address: 'Trương Định, Quận 1',
    description: 'Công viên cổ kính, nhiều cây xanh',
  },
  {
    id: 'park-3',
    name: 'Công viên Gia Định',
    type: 'park',
    lat: 10.8130,
    lng: 106.6850,
    address: 'Hoàng Minh Giám, Phú Nhuận',
    description: 'Khu vui chơi, thể thao',
  },

  // Trạm xe buýt
  {
    id: 'bus-1',
    name: 'Bến xe Miền Đông mới',
    type: 'bus_stop',
    lat: 10.8770,
    lng: 106.7810,
    address: 'Xa lộ Hà Nội, Thủ Đức',
    description: 'Bến xe liên tỉnh phía Đông',
  },
  {
    id: 'bus-2',
    name: 'Bến xe Miền Tây',
    type: 'bus_stop',
    lat: 10.7400,
    lng: 106.6170,
    address: '395 Kinh Dương Vương, Bình Tân',
    description: 'Bến xe liên tỉnh phía Tây',
  },
  {
    id: 'bus-3',
    name: 'Trạm xe buýt Bến Thành',
    type: 'bus_stop',
    lat: 10.7725,
    lng: 106.6980,
    address: 'Quách Thị Trang, Quận 1',
    description: 'Trạm trung tâm xe buýt',
  },
  {
    id: 'bus-4',
    name: 'Trạm xe buýt ĐH Bách Khoa',
    type: 'bus_stop',
    lat: 10.7730,
    lng: 106.6590,
    address: 'Lý Thường Kiệt, Quận 10',
    description: 'Trạm xe buýt sinh viên',
  },
];
